# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=256)),
                ('tip', models.IntegerField()),
                ('slika', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('adresa', models.CharField(max_length=256)),
                ('linije', models.CharField(max_length=256)),
                ('referenca', models.CharField(max_length=256)),
                ('brojac', models.BigIntegerField()),
            ],
        ),
    ]
