# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preporucivac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesto',
            name='x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesto',
            name='y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
