# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preporucivac', '0004_interesovanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesovanja',
            name='korIme',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
