# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preporucivac', '0005_interesovanja_korime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vreme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('opis', models.TextField()),
            ],
        ),
    ]
